### ISSUE TITLE
Composed name

### ISSUE THREAD

**Issue by mariefontanel** [johnotander/link_with_icon#4]
Hello, very good gem, however i can't use it with compound names of icons such as 'newspaper-o', 'quote-right' ...
Could you help me please ? 
I'd tried with an underscore:
<%= link_with_icon(:newspaper_o, ' my_link', link_name_url) %>
but it doesn't work !

**Comment by johno** [comment]
It _should_ work if you pass a string instead of a symbol like so:

```rb
<%= link_with_icon('newspaper-o', 'my_link', link_name_url) %>
```

Lemme know if that doesn't work for you, thanks!

**Comment by mariefontanel** [comment]
It works !!!!
Thanks
